[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
extra_scripts = pre:extra_script.py
upload_port = /dev/cu.usbserial-1110
upload_speed = 460800
monitor_port = /dev/cu.usbserial-1110
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
